service: aws-sls-swapi
frameworkVersion: '3'

custom:
  tableName: TasksTable

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  timeout: 30
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ TasksTable, Arn ]
  environment:
    TASKS_TABLE: ${self:custom.tableName}
    SWAPI_API_BASE: https://swapi.dev/api

plugins:
  - serverless-offline

functions:
  api:
    handler: app.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY

resources:
  Resources:
    TasksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
